development:
  server: "http://localhost:8080/faye"
  secret_token: "secret"
test:
  server: "http://localhost:8080/faye"
  secret_token: "secret"
production:
  server: "http://curripush.herokuapp.com/faye"
  secret_token: <%= ENV['PUSH_SECRET'] %>
  signature_expiration: 3600 # one hour
